cmd,devtools: fix errors reported by checks.bash
./checks.bash returned these errors from shellcheck and staticcheck,
which are now fixed:

In ./devtools/snapshot_vulndb.sh line 32:
for f in ${copyFiles[@]}; do
         ^-------------^ SC2068 (error): Double quote array expansions to avoid re-splitting elements.

In ./devtools/snapshot_vulndb.sh line 33:
  mkdir -p "$UNIT_OUT_DIR/$(dirname $f)" && curl -L $origin/$f --output $UNIT_OUT_DIR/$f
                                    ^-- SC2086 (info): Double quote to prevent globbing and word splitting.
                                                            ^-- SC2086 (info): Double quote to prevent globbing and word splitting.
                                                                        ^-----------^ SC2086 (info): Double quote to prevent globbing and word splitting.
                                                                                      ^-- SC2086 (info): Double quote to prevent globbing and word splitting.

Did you mean:
  mkdir -p "$UNIT_OUT_DIR/$(dirname "$f")" && curl -L $origin/"$f" --output "$UNIT_OUT_DIR"/"$f"

In ./devtools/snapshot_vulndb.sh line 37:
indexdb -out $UNIT_OUT_DIR -vulns $unit_vulns
             ^-----------^ SC2086 (info): Double quote to prevent globbing and word splitting.
                                  ^---------^ SC2086 (info): Double quote to prevent globbing and word splitting.

Did you mean:
indexdb -out "$UNIT_OUT_DIR" -vulns "$unit_vulns"

In ./devtools/snapshot_vulndb.sh line 51:
for f in ${copyFiles[@]}; do
         ^-------------^ SC2068 (error): Double quote array expansions to avoid re-splitting elements.

In ./devtools/snapshot_vulndb.sh line 52:
  mkdir -p "$INTEG_OUT_DIR/$(dirname $f)" && curl -L $origin/$f --output $INTEG_OUT_DIR/$f
                                     ^-- SC2086 (info): Double quote to prevent globbing and word splitting.
                                                             ^-- SC2086 (info): Double quote to prevent globbing and word splitting.
                                                                         ^------------^ SC2086 (info): Double quote to prevent globbing and word splitting.
                                                                                        ^-- SC2086 (info): Double quote to prevent globbing and word splitting.

Did you mean:
  mkdir -p "$INTEG_OUT_DIR/$(dirname "$f")" && curl -L $origin/"$f" --output "$INTEG_OUT_DIR"/"$f"

In ./devtools/snapshot_vulndb.sh line 56:
indexdb -out $INTEG_OUT_DIR -vulns $integ_vulns
             ^------------^ SC2086 (info): Double quote to prevent globbing and word splitting.
                                   ^----------^ SC2086 (info): Double quote to prevent globbing and word splitting.

Did you mean:
indexdb -out "$INTEG_OUT_DIR" -vulns "$integ_vulns"

cmd/govulncheck/integration/internal/integration/test.go:25:10: error strings should not be capitalized (ST1005)
cmd/govulncheck/integration/internal/integration/test.go:25:10: error strings should not end with punctuation or newlines (ST1005)

Change-Id: Ib0a204b113d5707f9e3d88d8dcbf0cef5622b3bf
Reviewed-on: https://go-review.googlesource.com/c/vuln/+/485236
Run-TryBot: Julie Qiu <julieqiu@google.com>
Reviewed-by: Julie Qiu <julieqiu@google.com>
Auto-Submit: Julie Qiu <julieqiu@google.com>
TryBot-Result: Gopher Robot <gobot@golang.org>
Reviewed-by: Tatiana Bradley <tatianabradley@google.com>
Run-TryBot: Julie Qiu <julie@golang.org>